name: Elixir CI

on: pull_request

jobs:
  test:
    name: Build & Test & FormatCheck
    runs-on: ubuntu-latest

    container:
      image: elixir:1.6-otp-21
      env:
        MIX_ENV: test

    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Test
        run: |
          mix test

      - name: Format Checks
        run: |
          mix format --check-formatted

